for
twtstudio/WePeiYang-Android pull request #14
Opened 2018-12-03 09:34 UTC by chenshuyuhhh

2018-12-03 13:13 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +    private val FOUND = 1
Should put constants in related data class but not activity

2018-12-03 13:14 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                if (myList.data!!.type == FOUND) {
Consider to check the null pointer

2018-12-04 05:33 UTC, rickygao requested changes

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                }
Consider to replace with
```kotlin
val images = myListDetailData.picture.orEmpty().map(Utils::getPicUrl)
```

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                        popupWindow.setOnDismissListener {
Why not put it in the above `apply` block

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                if (myList.data!!.type == FOUND) {
Consider to check the null pointer

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +    private val LOST = 2
Should put constants in related data class but not activity

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                    }
Why not `setDetail("标题", myListDetailData.title.orEmpty(), false)`?

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                    if (myListDetailData.detail_type != 2 && myListDetailData.type != 1) {
Should replace magic numbers with named constants

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                        if (myListDetailData.card_name != "null" && myListDetailData.card_name != null) {
Check exactly which condition can be true

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailItem.kt
> +fun MutableList<Item>.setDetail(specificTitle: String, content: String, isLast: Boolean) = add(DetailItem(specificTitle, content, isLast))
Why name it `setDetail`? Should come up with a better one, e.g. `detail`

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/OtherTagItem.kt
> +class OtherTagItem(val text3: String, val text2: String) : Item {
Parameters should have explicit names

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/OtherTagItem.kt
> +fun MutableList<Item>.setOther(text1: String, text2: String) = add(OtherTagItem(text1, text2))
Parameters should have explicit names, and name function a better name, `setFooBar` can be a setter of a property but not a normal function

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListActivity.kt
> +    private val WEIJINGLU = 2
Constants should be `const val`, if they are primitive types

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListActivity.kt
> +    private val WEIJINGLU = 2
And they should be in related `data class` but not in `Activity` or `Item`

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListActivity.kt
> +    private val WEIJINGLU = 2
`CAMPUS_BEI_YANG_YUAN` and `CAMPUS_WEI_JIN_LU` are better, `WEIJINGLU`???

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListFragment.kt
> +        lostOrFound = bundle!!.getString(Utils.INDEX_KEY)
remove `!!` and work with `?`, `?:` and a default value, or show a toast / message

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListFragment.kt
> +            override fun onScrolled(recyclerView: RecyclerView?, dx: Int, dy: Int) {
`recyclerView` can be `null`?

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListFragment.kt
> +            override fun generateDefaultLayoutParams(): RecyclerView.LayoutParams {
May replace with an expression function, e.g. `fun foo() = bar`

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListPagerAdapter.kt
> +        }
???

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListPresenterImpl.kt
> +                it.printStackTrace()
Log it or toast it

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListTableAdapter.kt
> +        val (id: Int, _: Int, _: String, title: String, place: String, time: String, _: String, detail_type: Int, isback: Int, picture: List<String>?, _: String?, _: Int?, campus: Int, isExpired: Int
wtf???

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListTableAdapter.kt
> +                        .load(Utils.getPicUrl("julao.jpg"))
???

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/release/ReleasePicAdapter.kt
> +            }
Store `list[position]` in a temporary `val`, and smart cast works

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/release/ReleasePicAdapter.kt
> +        }
`when` statement can handle it better

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/release/ReleasePicAdapter.kt
> +    }
A better choice is using "Null Object Pattern" instead of using bare `null`

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/release/ReleasePicAdapter.kt
> +        dialog.show()
Above can be included in a `apply` block

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchActivity.kt
> +    var campus: Int = 1
Replace magic numbers with constants

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchActivity.kt
> +    }
`val key: String get() = keyword`

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchActivity.kt
> +    }
or give `keyword` a public getter, maybe `lateinit` is not compatible with `getter`?

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchActivity.kt
> +    }
just use `keyword`

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchAdapter.kt
> +class SearchAdapter(var hr: MutableList<String>?, val activity: SearchInitActivity) : RecyclerView.Adapter<SearchAdapter.ViewHolder>() {
`hr` should have a clearer name, and be non-null

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchFragment.kt
> +        init()
No need

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchInitActivity.kt
> +    private fun getdatas() {
wtf `getdatas`

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchPresenterImpl.kt
> +            val campus = Utils.campus!!
reverse `if` and `=`, smart cast can work

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchInitActivity.kt
> +    private fun getdatas() {
❓

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/service/LostFoundService.kt
> +internal const val LOST_FOUND_BASE_URL = "https://open-lostfound.twtstudio.com/api/"
Make it `internal const val LOST_FOUND_BASE_URL = "https://open-lostfound.twtstudio.com/api/v1"`

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/service/LostFoundService.kt
> +internal const val LOST_FOUND_BASE_URL = "https://open-lostfound.twtstudio.com/api/"
And below should be `@GET("$LOST_FOUND_BASE_URL/path/to/service")`

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/service/Utils.kt
> +        }
Implement it with `List` or `Map`

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/service/Utils.kt
> +    companion object {
Why not `object Utils`? And why not just use top-level function

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/service/Utils.kt
> +        }
And helper list should be private

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/app/src/main/java/com/twt/service/WePeiYangApp.kt
> +            }
Use "if-expression"

2018-12-04 05:33 UTC, rickygao commented on WePeiYang/app/src/main/java/com/twt/service/WePeiYangApp.kt
> +                    customTheme = 0)
"Null Object Pattern" may help

2018-12-04 14:29 UTC, rickygao commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/release/ReleasePicAdapter.kt
> +            }
```kotlin
val tmp = list[position]
when (tmp) {
  is String -> ...
  is Uri -> ...
  else -> ...
}
```

2018-12-04 16:37 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                }
已修改

2018-12-04 16:39 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                        popupWindow.setOnDismissListener {
已修改

2018-12-04 16:54 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                if (myList.data!!.type == FOUND) {
好滴

2018-12-04 16:54 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +    private val LOST = 2
已修改

2018-12-04 17:00 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                    }
已修改

2018-12-04 17:04 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                    if (myListDetailData.detail_type != 2 && myListDetailData.type != 1) {
已修改

2018-12-04 17:04 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailActivity.kt
> +                        if (myListDetailData.card_name != "null" && myListDetailData.card_name != null) {
后台给的数据，莫得办法

2018-12-04 17:06 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/DetailItem.kt
> +fun MutableList<Item>.setDetail(specificTitle: String, content: String, isLast: Boolean) = add(DetailItem(specificTitle, content, isLast))
已修改

2018-12-04 17:09 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/OtherTagItem.kt
> +class OtherTagItem(val text3: String, val text2: String) : Item {
已修改

2018-12-04 17:13 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/detail/OtherTagItem.kt
> +fun MutableList<Item>.setOther(text1: String, text2: String) = add(OtherTagItem(text1, text2))
已修改

2018-12-04 17:20 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListActivity.kt
> +    private val WEIJINGLU = 2
已修改

2018-12-04 17:29 UTC, stellasuc commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListFragment.kt
> +        lostOrFound = bundle!!.getString(Utils.INDEX_KEY)
已修改

2018-12-04 17:29 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListFragment.kt
> +            override fun onScrolled(recyclerView: RecyclerView?, dx: Int, dy: Int) {
已修改

2018-12-04 17:31 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListFragment.kt
> +            override fun generateDefaultLayoutParams(): RecyclerView.LayoutParams {
已修改

2018-12-04 17:32 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListPagerAdapter.kt
> +        }
已删掉

2018-12-04 17:32 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListPresenterImpl.kt
> +                it.printStackTrace()
已修改

2018-12-04 17:41 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListTableAdapter.kt
> +        val (id: Int, _: Int, _: String, title: String, place: String, time: String, _: String, detail_type: Int, isback: Int, picture: List<String>?, _: String?, _: Int?, campus: Int, isExpired: Int
已修改方法

2018-12-04 17:41 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/mylist/MyListTableAdapter.kt
> +                        .load(Utils.getPicUrl("julao.jpg"))
已修改

2018-12-04 17:44 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchActivity.kt
> +    var campus: Int = 1
这都不是常量，后面要修改的

2018-12-04 17:53 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchAdapter.kt
> +class SearchAdapter(var hr: MutableList<String>?, val activity: SearchInitActivity) : RecyclerView.Adapter<SearchAdapter.ViewHolder>() {
已修改

2018-12-04 17:54 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchFragment.kt
> +        init()
已修改

2018-12-04 17:55 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchInitActivity.kt
> +    private fun getdatas() {
已修改_

2018-12-04 17:56 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchPresenterImpl.kt
> +            val campus = Utils.campus!!
已修改

2018-12-04 18:00 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/service/LostFoundService.kt
> +internal const val LOST_FOUND_BASE_URL = "https://open-lostfound.twtstudio.com/api/"
已修改

2018-12-05 05:25 UTC, stellasuc commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/service/Utils.kt
> +        }
已修改

2018-12-05 05:25 UTC, stellasuc commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/service/Utils.kt
> +    companion object {
已修改

2018-12-05 08:23 UTC, WingedVampires commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/release/ReleasePicAdapter.kt
> +            }
已修改

2018-12-05 08:24 UTC, WingedVampires commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/release/ReleasePicAdapter.kt
> +        }
已修改

2018-12-05 08:37 UTC, WingedVampires commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/release/ReleasePicAdapter.kt
> +    }
已修改

2018-12-05 08:54 UTC, WingedVampires commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/release/ReleasePicAdapter.kt
> +        dialog.show()
上面那个dialog它已经在一个apply块中，两个dialog不适合用apply

2018-12-05 09:00 UTC, WingedVampires commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/release/ReleasePicAdapter.kt
> +        dialog.show()
已修改

2018-12-05 13:15 UTC, chenshuyuhhh commented on WePeiYang/lostfound2/src/main/java/com/yookiely/lostfond2/search/SearchActivity.kt
> +    }
已修改

2018-12-05 13:29 UTC, closed without merging